experiment_name: "reproduce2"

models_to_run:
  - FANPhaseOffsetModelGated
#  - FANAmplitudePhaseModel
#  - FANMultiFrequencyModel
#  - FANUnconstrainedBasisModel
#  - FANPhaseOffsetModel
  - FANGated
#  - FAN
#  - MLP
#  - FANPhaseOffsetModelGated
#  - FANPhaseOffsetModel
#  - FANGated
#  - FAN
#  - MLP

datasets_to_run:
#  - complex_3
#  - sin
  - increasing_amp_freq
#  - mod
#  - complex_2
#  - complex_1
#  - complex_4


data_versions:
  - original
#  - noisy
#  - sparse

hyperparameters:
  early_stopping: False
  early_stopping_patience: 300
  early_stopping_min_delta: 0.000001
  num_samples: 10000
  test_samples: 4000
  noise_level: 0.15
  sparsity_factor: 0.5
  epochs: 1000
  lr: 0.00001

logging:
  level: "INFO"  # Could be DEBUG, INFO, WARNING, ERROR, etc.

random_seed: 42