experiment_name: "many model viz"

models_to_run:
  - FANPhaseOffsetModelGated
  - FANPhaseOffsetModel
  - FANGated
  - FAN
  - MLP

datasets_to_run:
  - sin
  - mod

data_versions:
  - original
  - noisy
#  - sparse

hyperparameters:
  early_stopping: False
  early_stopping_patience: 200
  early_stopping_min_delta: 0.00001
  num_samples: 10000
  test_samples: 4000
  noise_level: 0.15
  sparsity_factor: 0.5
  epochs: 50
  lr: 0.00001

logging:
  level: "INFO"  # Could be DEBUG, INFO, WARNING, ERROR, etc.

random_seed: 42