experiment_name: "run "

models_to_run:
  - FANPhaseOffsetModel
  - FANPhaseOffsetModelLimited
  - FANOffsetOnlyCosModel
  - FANGated
  - MLP
  - FAN

datasets_to_run:
  - complex_1
  - complex_2
  - sin
  - mod

data_versions:
  - original
  - noisy
#  - sparse

hyperparameters:
  early_stopping: True
  early_stopping_patience: 100
  early_stopping_min_delta: 0.001
  num_samples: 10000
  test_samples: 4000
  noise_level: 0.15
  sparsity_factor: 0.5
  epochs: 10000
  lr: 0.001

logging:
  level: "INFO"  # Could be DEBUG, INFO, WARNING, ERROR, etc.

random_seed: 42

# Visualization settings
visualization:
  offset_loss: True  # Enable tracking and plotting of phase offset parameters
  plot_offset_convergence: True  # Generate convergence plot for all offset parameters
  zoom_y_axis: True  # Zoom y-axis to actual data range on offset plots
  add_reference_lines: False  # Don't add reference lines for π/4, π/2, etc.