experiment_name: "etth1"

models_to_run:
  - FANGatedForecaster
#  - FANPhaseOffsetModelGated
#  - FANPhaseOffsetModel
#  - FANGated
#  - FAN
#  - MLP

datasets_to_run:
  - etth1

data_versions:
  - original
  - noisy
#  - sparse

hyperparameters:
  early_stopping: False
  early_stopping_patience: 200
  early_stopping_min_delta: 0.00001
  num_samples: 10000
  test_samples: 4000
  noise_level: 0.15
  sparsity_factor: 0.5
  epochs: 50
  lr: 0.00001


  # Time series specific parameters
  seq_len: 96
  pred_len: 24
  target_col: "OT"
  hidden_dim: 64
  normalize: True
  train_ratio: 0.7
  val_ratio: 0.1
  include_val_in_train: True
  data_dir: "data"

logging:
  level: "INFO"  # Could be DEBUG, INFO, WARNING, ERROR, etc.

random_seed: 42