experiment_name: "run"

models_to_run:
  - FANPhaseOffsetModel
  - FANPhaseOffsetModelUniform
  - FANPhaseOffsetModelLimited
  - FANOffsetOnlyCosModel
  - FANGated
  - MLP
  - FAN

datasets_to_run:
  - complex_1
  - complex_2
  - sin
  - mod

data_versions:
  - original
  - noisy
  # - sparse

hyperparameters:
  # Early stopping
  early_stopping: True
  early_stopping_patience: 100
  early_stopping_min_delta: 0.001
  
  # Data parameters
  num_samples: 10000
  test_samples: 4000
  noise_level: 0.15
  sparsity_factor: 0.5
  
  # Training parameters
  epochs: 10000
  lr: 0.001

logging:
  level: "INFO"

random_seed: 42